package com.chikuwa_latte.core.mapper.db_transaction;

import com.chikuwa_latte.core.entity.db_transaction.Battle;
import com.chikuwa_latte.core.entity.db_transaction.BattleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BattleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    long countByExample(BattleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int deleteByExample(BattleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int insert(Battle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int insertSelective(Battle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    List<Battle> selectByExample(BattleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    Battle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Battle row, @Param("example") BattleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Battle row, @Param("example") BattleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Battle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table battle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Battle row);
}