package com.chikuwa_latte.core.mapper.db_user;

import com.chikuwa_latte.core.entity.db_user.UserFlywaySchemaHistory;
import com.chikuwa_latte.core.entity.db_user.UserFlywaySchemaHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserFlywaySchemaHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    long countByExample(UserFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int deleteByExample(UserFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int insert(UserFlywaySchemaHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int insertSelective(UserFlywaySchemaHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    List<UserFlywaySchemaHistory> selectByExample(UserFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    UserFlywaySchemaHistory selectByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") UserFlywaySchemaHistory row, @Param("example") UserFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") UserFlywaySchemaHistory row, @Param("example") UserFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFlywaySchemaHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFlywaySchemaHistory row);
}