package com.chikuwa_latte.core.mapper.db_master;

import com.chikuwa_latte.core.entity.db_master.MasterFlywaySchemaHistory;
import com.chikuwa_latte.core.entity.db_master.MasterFlywaySchemaHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MasterFlywaySchemaHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    long countByExample(MasterFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int deleteByExample(MasterFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int insert(MasterFlywaySchemaHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int insertSelective(MasterFlywaySchemaHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    List<MasterFlywaySchemaHistory> selectByExample(MasterFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    MasterFlywaySchemaHistory selectByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MasterFlywaySchemaHistory row, @Param("example") MasterFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MasterFlywaySchemaHistory row, @Param("example") MasterFlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MasterFlywaySchemaHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_flyway_schema_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MasterFlywaySchemaHistory row);
}