package com.chikuwa_latte.core.mapper.db_master;

import com.chikuwa_latte.core.entity.db_master.MasterTable01;
import com.chikuwa_latte.core.entity.db_master.MasterTable01Example;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MasterTable01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    long countByExample(MasterTable01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int deleteByExample(MasterTable01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int insert(MasterTable01 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int insertSelective(MasterTable01 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    List<MasterTable01> selectByExample(MasterTable01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    MasterTable01 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MasterTable01 row, @Param("example") MasterTable01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MasterTable01 row, @Param("example") MasterTable01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MasterTable01 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_table_01
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MasterTable01 row);
}