service:
    message: Hello, World!OHOHOHOH

spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        db-master:
            jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_master
            username: admin
            password: admin
            driver-class-name: com.mysql.cj.jdbc.Driver
        db-user:
            jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_user
            username: admin
            password: admin
            driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        baseline-version: 0
        # DefaultConfigration.javaにFlywayの設定を記述したため、ここはfalseにする
        enabled: false
        baseline-on-migrate: true
    devtools:
        restart:
            enabled: true

mybatis:
    configuration:
        map-underscore-to-camel-case: true

# ログ: 必要に応じてコメントアウトを解除
# logging:
#     level:
#         root: INFO  # 全体のデフォルトログレベル
#         org.springframework: DEBUG  # Spring のログを DEBUG レベルで出力
#         org.mybatis: TRACE  # MyBatis のログを TRACE レベルで出力
#         com.zaxxer.hikari: DEBUG  # HikariCP のログを DEBUG レベルで出力
#         com.chikuwa_latte: DEBUG  # 自分のプロジェクトのログを DEBUG レベルで出力
#     file:
#         path: ./log/application.log  # ログをファイルに保存