package com.chikuwa_latte.core.entity.db_master;

import com.chikuwa_latte.core.constant.AttributeType;
import java.util.ArrayList;
import java.util.List;

public class MonsterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monster
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monster
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monster
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public MonsterExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monster
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monster
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMonsterNameIsNull() {
            addCriterion("monster_name is null");
            return (Criteria) this;
        }

        public Criteria andMonsterNameIsNotNull() {
            addCriterion("monster_name is not null");
            return (Criteria) this;
        }

        public Criteria andMonsterNameEqualTo(String value) {
            addCriterion("monster_name =", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameNotEqualTo(String value) {
            addCriterion("monster_name <>", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameGreaterThan(String value) {
            addCriterion("monster_name >", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameGreaterThanOrEqualTo(String value) {
            addCriterion("monster_name >=", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameLessThan(String value) {
            addCriterion("monster_name <", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameLessThanOrEqualTo(String value) {
            addCriterion("monster_name <=", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameLike(String value) {
            addCriterion("monster_name like", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameNotLike(String value) {
            addCriterion("monster_name not like", value, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameIn(List<String> values) {
            addCriterion("monster_name in", values, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameNotIn(List<String> values) {
            addCriterion("monster_name not in", values, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameBetween(String value1, String value2) {
            addCriterion("monster_name between", value1, value2, "monsterName");
            return (Criteria) this;
        }

        public Criteria andMonsterNameNotBetween(String value1, String value2) {
            addCriterion("monster_name not between", value1, value2, "monsterName");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeIsNull() {
            addCriterion("attribute_type is null");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeIsNotNull() {
            addCriterion("attribute_type is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeEqualTo(AttributeType value) {
            addCriterion("attribute_type =", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeNotEqualTo(AttributeType value) {
            addCriterion("attribute_type <>", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeGreaterThan(AttributeType value) {
            addCriterion("attribute_type >", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeGreaterThanOrEqualTo(AttributeType value) {
            addCriterion("attribute_type >=", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeLessThan(AttributeType value) {
            addCriterion("attribute_type <", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeLessThanOrEqualTo(AttributeType value) {
            addCriterion("attribute_type <=", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeLike(AttributeType value) {
            addCriterion("attribute_type like", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeNotLike(AttributeType value) {
            addCriterion("attribute_type not like", value, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeIn(List<AttributeType> values) {
            addCriterion("attribute_type in", values, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeNotIn(List<AttributeType> values) {
            addCriterion("attribute_type not in", values, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeBetween(AttributeType value1, AttributeType value2) {
            addCriterion("attribute_type between", value1, value2, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeTypeNotBetween(AttributeType value1, AttributeType value2) {
            addCriterion("attribute_type not between", value1, value2, "attributeType");
            return (Criteria) this;
        }

        public Criteria andAttributeType2IsNull() {
            addCriterion("attribute_type_2 is null");
            return (Criteria) this;
        }

        public Criteria andAttributeType2IsNotNull() {
            addCriterion("attribute_type_2 is not null");
            return (Criteria) this;
        }

        public Criteria andAttributeType2EqualTo(String value) {
            addCriterion("attribute_type_2 =", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2NotEqualTo(String value) {
            addCriterion("attribute_type_2 <>", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2GreaterThan(String value) {
            addCriterion("attribute_type_2 >", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2GreaterThanOrEqualTo(String value) {
            addCriterion("attribute_type_2 >=", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2LessThan(String value) {
            addCriterion("attribute_type_2 <", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2LessThanOrEqualTo(String value) {
            addCriterion("attribute_type_2 <=", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2Like(String value) {
            addCriterion("attribute_type_2 like", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2NotLike(String value) {
            addCriterion("attribute_type_2 not like", value, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2In(List<String> values) {
            addCriterion("attribute_type_2 in", values, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2NotIn(List<String> values) {
            addCriterion("attribute_type_2 not in", values, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2Between(String value1, String value2) {
            addCriterion("attribute_type_2 between", value1, value2, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andAttributeType2NotBetween(String value1, String value2) {
            addCriterion("attribute_type_2 not between", value1, value2, "attributeType2");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdIsNull() {
            addCriterion("capability_id is null");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdIsNotNull() {
            addCriterion("capability_id is not null");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdEqualTo(Integer value) {
            addCriterion("capability_id =", value, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdNotEqualTo(Integer value) {
            addCriterion("capability_id <>", value, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdGreaterThan(Integer value) {
            addCriterion("capability_id >", value, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("capability_id >=", value, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdLessThan(Integer value) {
            addCriterion("capability_id <", value, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdLessThanOrEqualTo(Integer value) {
            addCriterion("capability_id <=", value, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdIn(List<Integer> values) {
            addCriterion("capability_id in", values, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdNotIn(List<Integer> values) {
            addCriterion("capability_id not in", values, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdBetween(Integer value1, Integer value2) {
            addCriterion("capability_id between", value1, value2, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andCapabilityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("capability_id not between", value1, value2, "capabilityId");
            return (Criteria) this;
        }

        public Criteria andHpIsNull() {
            addCriterion("hp is null");
            return (Criteria) this;
        }

        public Criteria andHpIsNotNull() {
            addCriterion("hp is not null");
            return (Criteria) this;
        }

        public Criteria andHpEqualTo(Integer value) {
            addCriterion("hp =", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotEqualTo(Integer value) {
            addCriterion("hp <>", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpGreaterThan(Integer value) {
            addCriterion("hp >", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpGreaterThanOrEqualTo(Integer value) {
            addCriterion("hp >=", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpLessThan(Integer value) {
            addCriterion("hp <", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpLessThanOrEqualTo(Integer value) {
            addCriterion("hp <=", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpIn(List<Integer> values) {
            addCriterion("hp in", values, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotIn(List<Integer> values) {
            addCriterion("hp not in", values, "hp");
            return (Criteria) this;
        }

        public Criteria andHpBetween(Integer value1, Integer value2) {
            addCriterion("hp between", value1, value2, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotBetween(Integer value1, Integer value2) {
            addCriterion("hp not between", value1, value2, "hp");
            return (Criteria) this;
        }

        public Criteria andAttackIsNull() {
            addCriterion("attack is null");
            return (Criteria) this;
        }

        public Criteria andAttackIsNotNull() {
            addCriterion("attack is not null");
            return (Criteria) this;
        }

        public Criteria andAttackEqualTo(Integer value) {
            addCriterion("attack =", value, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackNotEqualTo(Integer value) {
            addCriterion("attack <>", value, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackGreaterThan(Integer value) {
            addCriterion("attack >", value, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackGreaterThanOrEqualTo(Integer value) {
            addCriterion("attack >=", value, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackLessThan(Integer value) {
            addCriterion("attack <", value, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackLessThanOrEqualTo(Integer value) {
            addCriterion("attack <=", value, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackIn(List<Integer> values) {
            addCriterion("attack in", values, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackNotIn(List<Integer> values) {
            addCriterion("attack not in", values, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackBetween(Integer value1, Integer value2) {
            addCriterion("attack between", value1, value2, "attack");
            return (Criteria) this;
        }

        public Criteria andAttackNotBetween(Integer value1, Integer value2) {
            addCriterion("attack not between", value1, value2, "attack");
            return (Criteria) this;
        }

        public Criteria andDefenseIsNull() {
            addCriterion("defense is null");
            return (Criteria) this;
        }

        public Criteria andDefenseIsNotNull() {
            addCriterion("defense is not null");
            return (Criteria) this;
        }

        public Criteria andDefenseEqualTo(Integer value) {
            addCriterion("defense =", value, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseNotEqualTo(Integer value) {
            addCriterion("defense <>", value, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseGreaterThan(Integer value) {
            addCriterion("defense >", value, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseGreaterThanOrEqualTo(Integer value) {
            addCriterion("defense >=", value, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseLessThan(Integer value) {
            addCriterion("defense <", value, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseLessThanOrEqualTo(Integer value) {
            addCriterion("defense <=", value, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseIn(List<Integer> values) {
            addCriterion("defense in", values, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseNotIn(List<Integer> values) {
            addCriterion("defense not in", values, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseBetween(Integer value1, Integer value2) {
            addCriterion("defense between", value1, value2, "defense");
            return (Criteria) this;
        }

        public Criteria andDefenseNotBetween(Integer value1, Integer value2) {
            addCriterion("defense not between", value1, value2, "defense");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackIsNull() {
            addCriterion("special_attack is null");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackIsNotNull() {
            addCriterion("special_attack is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackEqualTo(Integer value) {
            addCriterion("special_attack =", value, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackNotEqualTo(Integer value) {
            addCriterion("special_attack <>", value, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackGreaterThan(Integer value) {
            addCriterion("special_attack >", value, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackGreaterThanOrEqualTo(Integer value) {
            addCriterion("special_attack >=", value, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackLessThan(Integer value) {
            addCriterion("special_attack <", value, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackLessThanOrEqualTo(Integer value) {
            addCriterion("special_attack <=", value, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackIn(List<Integer> values) {
            addCriterion("special_attack in", values, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackNotIn(List<Integer> values) {
            addCriterion("special_attack not in", values, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackBetween(Integer value1, Integer value2) {
            addCriterion("special_attack between", value1, value2, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialAttackNotBetween(Integer value1, Integer value2) {
            addCriterion("special_attack not between", value1, value2, "specialAttack");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseIsNull() {
            addCriterion("special_defense is null");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseIsNotNull() {
            addCriterion("special_defense is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseEqualTo(Integer value) {
            addCriterion("special_defense =", value, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseNotEqualTo(Integer value) {
            addCriterion("special_defense <>", value, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseGreaterThan(Integer value) {
            addCriterion("special_defense >", value, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseGreaterThanOrEqualTo(Integer value) {
            addCriterion("special_defense >=", value, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseLessThan(Integer value) {
            addCriterion("special_defense <", value, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseLessThanOrEqualTo(Integer value) {
            addCriterion("special_defense <=", value, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseIn(List<Integer> values) {
            addCriterion("special_defense in", values, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseNotIn(List<Integer> values) {
            addCriterion("special_defense not in", values, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseBetween(Integer value1, Integer value2) {
            addCriterion("special_defense between", value1, value2, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpecialDefenseNotBetween(Integer value1, Integer value2) {
            addCriterion("special_defense not between", value1, value2, "specialDefense");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNull() {
            addCriterion("speed is null");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNotNull() {
            addCriterion("speed is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedEqualTo(Integer value) {
            addCriterion("speed =", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotEqualTo(Integer value) {
            addCriterion("speed <>", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThan(Integer value) {
            addCriterion("speed >", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("speed >=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThan(Integer value) {
            addCriterion("speed <", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThanOrEqualTo(Integer value) {
            addCriterion("speed <=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedIn(List<Integer> values) {
            addCriterion("speed in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotIn(List<Integer> values) {
            addCriterion("speed not in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedBetween(Integer value1, Integer value2) {
            addCriterion("speed between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotBetween(Integer value1, Integer value2) {
            addCriterion("speed not between", value1, value2, "speed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monster
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monster
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}