package com.chikuwa_latte.core.entity.db_master;

import com.chikuwa_latte.core.constant.AbilityType;
import com.chikuwa_latte.core.constant.Ailment;
import com.chikuwa_latte.core.constant.AttributeType;
import com.chikuwa_latte.core.constant.CriticalRateType;
import com.chikuwa_latte.core.constant.EffectType;
import com.chikuwa_latte.core.constant.SkillType;
import java.io.Serializable;

public class Skill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_type
     *
     * @mbg.generated
     */
    private SkillType skillType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.attribute_type
     *
     * @mbg.generated
     */
    private AttributeType attributeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.power
     *
     * @mbg.generated
     */
    private Integer power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.hit_rate
     *
     * @mbg.generated
     */
    private Integer hitRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.critical_rate_type
     *
     * @mbg.generated
     */
    private CriticalRateType criticalRateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.effect_type
     *
     * @mbg.generated
     */
    private EffectType effectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.effect_rate
     *
     * @mbg.generated
     */
    private Integer effectRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.ailment
     *
     * @mbg.generated
     */
    private Ailment ailment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.ability_type
     *
     * @mbg.generated
     */
    private AbilityType abilityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.ability_control_value
     *
     * @mbg.generated
     */
    private Integer abilityControlValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.skill_other_effectId
     *
     * @mbg.generated
     */
    private Integer skillOtherEffectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated
     */
    public Skill(Integer id, SkillType skillType, AttributeType attributeType, Integer power, Integer hitRate, CriticalRateType criticalRateType, EffectType effectType, Integer effectRate, Ailment ailment, AbilityType abilityType, Integer abilityControlValue, Integer skillOtherEffectid) {
        this.id = id;
        this.skillType = skillType;
        this.attributeType = attributeType;
        this.power = power;
        this.hitRate = hitRate;
        this.criticalRateType = criticalRateType;
        this.effectType = effectType;
        this.effectRate = effectRate;
        this.ailment = ailment;
        this.abilityType = abilityType;
        this.abilityControlValue = abilityControlValue;
        this.skillOtherEffectid = skillOtherEffectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated
     */
    public Skill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.id
     *
     * @return the value of skill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.id
     *
     * @param id the value for skill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.skill_type
     *
     * @return the value of skill.skill_type
     *
     * @mbg.generated
     */
    public SkillType getSkillType() {
        return skillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.skill_type
     *
     * @param skillType the value for skill.skill_type
     *
     * @mbg.generated
     */
    public void setSkillType(SkillType skillType) {
        this.skillType = skillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.attribute_type
     *
     * @return the value of skill.attribute_type
     *
     * @mbg.generated
     */
    public AttributeType getAttributeType() {
        return attributeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.attribute_type
     *
     * @param attributeType the value for skill.attribute_type
     *
     * @mbg.generated
     */
    public void setAttributeType(AttributeType attributeType) {
        this.attributeType = attributeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.power
     *
     * @return the value of skill.power
     *
     * @mbg.generated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.power
     *
     * @param power the value for skill.power
     *
     * @mbg.generated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.hit_rate
     *
     * @return the value of skill.hit_rate
     *
     * @mbg.generated
     */
    public Integer getHitRate() {
        return hitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.hit_rate
     *
     * @param hitRate the value for skill.hit_rate
     *
     * @mbg.generated
     */
    public void setHitRate(Integer hitRate) {
        this.hitRate = hitRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.critical_rate_type
     *
     * @return the value of skill.critical_rate_type
     *
     * @mbg.generated
     */
    public CriticalRateType getCriticalRateType() {
        return criticalRateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.critical_rate_type
     *
     * @param criticalRateType the value for skill.critical_rate_type
     *
     * @mbg.generated
     */
    public void setCriticalRateType(CriticalRateType criticalRateType) {
        this.criticalRateType = criticalRateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.effect_type
     *
     * @return the value of skill.effect_type
     *
     * @mbg.generated
     */
    public EffectType getEffectType() {
        return effectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.effect_type
     *
     * @param effectType the value for skill.effect_type
     *
     * @mbg.generated
     */
    public void setEffectType(EffectType effectType) {
        this.effectType = effectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.effect_rate
     *
     * @return the value of skill.effect_rate
     *
     * @mbg.generated
     */
    public Integer getEffectRate() {
        return effectRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.effect_rate
     *
     * @param effectRate the value for skill.effect_rate
     *
     * @mbg.generated
     */
    public void setEffectRate(Integer effectRate) {
        this.effectRate = effectRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.ailment
     *
     * @return the value of skill.ailment
     *
     * @mbg.generated
     */
    public Ailment getAilment() {
        return ailment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.ailment
     *
     * @param ailment the value for skill.ailment
     *
     * @mbg.generated
     */
    public void setAilment(Ailment ailment) {
        this.ailment = ailment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.ability_type
     *
     * @return the value of skill.ability_type
     *
     * @mbg.generated
     */
    public AbilityType getAbilityType() {
        return abilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.ability_type
     *
     * @param abilityType the value for skill.ability_type
     *
     * @mbg.generated
     */
    public void setAbilityType(AbilityType abilityType) {
        this.abilityType = abilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.ability_control_value
     *
     * @return the value of skill.ability_control_value
     *
     * @mbg.generated
     */
    public Integer getAbilityControlValue() {
        return abilityControlValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.ability_control_value
     *
     * @param abilityControlValue the value for skill.ability_control_value
     *
     * @mbg.generated
     */
    public void setAbilityControlValue(Integer abilityControlValue) {
        this.abilityControlValue = abilityControlValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.skill_other_effectId
     *
     * @return the value of skill.skill_other_effectId
     *
     * @mbg.generated
     */
    public Integer getSkillOtherEffectid() {
        return skillOtherEffectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.skill_other_effectId
     *
     * @param skillOtherEffectid the value for skill.skill_other_effectId
     *
     * @mbg.generated
     */
    public void setSkillOtherEffectid(Integer skillOtherEffectid) {
        this.skillOtherEffectid = skillOtherEffectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Skill other = (Skill) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSkillType() == null ? other.getSkillType() == null : this.getSkillType().equals(other.getSkillType()))
            && (this.getAttributeType() == null ? other.getAttributeType() == null : this.getAttributeType().equals(other.getAttributeType()))
            && (this.getPower() == null ? other.getPower() == null : this.getPower().equals(other.getPower()))
            && (this.getHitRate() == null ? other.getHitRate() == null : this.getHitRate().equals(other.getHitRate()))
            && (this.getCriticalRateType() == null ? other.getCriticalRateType() == null : this.getCriticalRateType().equals(other.getCriticalRateType()))
            && (this.getEffectType() == null ? other.getEffectType() == null : this.getEffectType().equals(other.getEffectType()))
            && (this.getEffectRate() == null ? other.getEffectRate() == null : this.getEffectRate().equals(other.getEffectRate()))
            && (this.getAilment() == null ? other.getAilment() == null : this.getAilment().equals(other.getAilment()))
            && (this.getAbilityType() == null ? other.getAbilityType() == null : this.getAbilityType().equals(other.getAbilityType()))
            && (this.getAbilityControlValue() == null ? other.getAbilityControlValue() == null : this.getAbilityControlValue().equals(other.getAbilityControlValue()))
            && (this.getSkillOtherEffectid() == null ? other.getSkillOtherEffectid() == null : this.getSkillOtherEffectid().equals(other.getSkillOtherEffectid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSkillType() == null) ? 0 : getSkillType().hashCode());
        result = prime * result + ((getAttributeType() == null) ? 0 : getAttributeType().hashCode());
        result = prime * result + ((getPower() == null) ? 0 : getPower().hashCode());
        result = prime * result + ((getHitRate() == null) ? 0 : getHitRate().hashCode());
        result = prime * result + ((getCriticalRateType() == null) ? 0 : getCriticalRateType().hashCode());
        result = prime * result + ((getEffectType() == null) ? 0 : getEffectType().hashCode());
        result = prime * result + ((getEffectRate() == null) ? 0 : getEffectRate().hashCode());
        result = prime * result + ((getAilment() == null) ? 0 : getAilment().hashCode());
        result = prime * result + ((getAbilityType() == null) ? 0 : getAbilityType().hashCode());
        result = prime * result + ((getAbilityControlValue() == null) ? 0 : getAbilityControlValue().hashCode());
        result = prime * result + ((getSkillOtherEffectid() == null) ? 0 : getSkillOtherEffectid().hashCode());
        return result;
    }
}